branches:
  only:
    - master

cache:
  directories:
    - "node_modules"

dist: trusty

language: node_js
node_js:
  - "8"

script: ""

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
